services:
  next:
    image: ghcr.io/debutyohan/devops-project/nodejs-my-website:dev
    ports:
      - 3001:3000
  db:
    image: mariadb:10.6
    environment: # Variables d'environnement
      MARIADB_DATABASE: cube
      MARIADB_USER: cube
      MARIADB_PASSWORD: cube
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./next-dev/docker/db/data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8081:8080