name: my-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run build
      - run: ls -rtl
      - uses: actions/cache/save@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: videos-cypress-tests
          path: cypress/videos