name: my-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build-next-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run build
      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: videos-cypress-tests
          path: cypress/videos